name: Build (template)

permissions:
  contents: read

on:
  push:
    tags:
    - '*'
  release:
    types: [created]

jobs:
  call-workflow:
    uses: eumel8/workflow-templates/.github/workflows/build.yaml@0.0.8
