# https://github.com/marketplace/actions/go-release-binaries
name: Build fyne-app
on:
  push:
    tags:        
      - '*'
    branches:
      - dev
  release:
    types: [created]

permissions:
  contents: write

jobs:
  fyne-cross-and-release:
    name: build and release 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v6
      with:
        go-version: '1.24.6'
    - name: install packages
      run: |
          go version
          sudo apt update
          sudo apt-get -y install bc gcc libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb
          #go install github.com/fyne-io/fyne-cross@v2.7.3
          #go install github.com/tcnksm/ghr@v0.17.0
    - name: compile
      run: |
          export PATH=$PATH:~/go/bin
          fyne-cross linux -output capi-advisor -arch=amd64,arm64,arm -debug .
          ls -lR fyne-cross
    - name: package
      run: |
          cd fyne-cross/bin/linux-arm64/; tar cvfz capi-advisor-arm64.tgz capi-advisor; cd ../../..
          cd fyne-cross/bin/linux-arm/; tar cvfz capi-advisor-arm.tgz capi-advisor; cd ../../..
          cd fyne-cross/bin/linux-amd64/; tar cvfz capi-advisor-amd64.tgz capi-advisor; cd ../../..
    - name: Release linux-amd64
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: fyne-cross/bin/linux-amd64/capi-advisor-amd64.tgz
        GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        GHR_REPLACE: true
        GOTOOLCHAIN: go1.24.6
    - name: Release linux-arm64
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: fyne-cross/bin/linux-arm64/capi-advisor-arm64.tgz
        GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        GHR_REPLACE: true
        GOTOOLCHAIN: go1.24.6
    - name: Release linux-arm
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: fyne-cross/bin/linux-arm/capi-advisor-arm.tgz
        GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        GHR_REPLACE: true
        GOTOOLCHAIN: go1.24.6

